name: Build Binaries
on: 
  release:
    types:
      - created
jobs:
  build_for_linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/lurk lurk-linux-amd64
      - name: Upload to release
        uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
        with:
          args: lurk-linux-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}